# Generated by Django 5.0.7 on 2024-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
            ],
        ),
    ]
