# Generated by Django 5.0.7 on 2024-07-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category_alter_product_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
