# Generated by Django 5.0.7 on 2024-07-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productmatching_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('ModelNo', models.IntegerField()),
                ('PartNo', models.IntegerField()),
                ('SerialNo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_matching',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductMatching',
        ),
    ]
