# Generated by Django 5.0.7 on 2024-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_scannedproduct_delete_prod1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
